/**
 * Text Export for Reports
 * Generates plain text/markdown formatted reports for sharing
 */

import { DoctorSummary, ReportMetadata } from './doctor-summary'

export function generateTextReport(
  summary: DoctorSummary,
  metadata: ReportMetadata
): string {
  const lines: string[] = []
  
  // Header
  lines.push('WEARABLE HEALTH SUMMARY REPORT')
  lines.push('='.repeat(50))
  lines.push('')
  lines.push(`Patient email: ${metadata.patientEmail}`)
  lines.push(`Report date: ${metadata.reportDate}`)
  lines.push(`7 Days values: ${metadata.dataPeriod.start} – ${metadata.dataPeriod.end} (${metadata.dataPeriod.days} days)`)
  lines.push(`30 Days Reference Range: ${metadata.referenceRange.start} – ${metadata.referenceRange.end} (${metadata.referenceRange.days} days)`)
  lines.push('')
  lines.push('')
  
  // Sleep Summary
  if (summary.sleepTable.length > 0) {
    lines.push('SLEEP SUMMARY')
    lines.push('-'.repeat(50))
    lines.push('')
    lines.push(formatTable(summary.sleepTable))
    lines.push('')
  }
  
  // Cardiovascular & Oxygenation
  if (summary.cardiovascularTable.length > 0) {
    lines.push('CARDIOVASCULAR & OXYGENATION')
    lines.push('-'.repeat(50))
    lines.push('')
    lines.push(formatTable(summary.cardiovascularTable))
    lines.push('')
  }
  
  // Activity
  if (summary.activityTable.length > 0) {
    lines.push('ACTIVITY')
    lines.push('-'.repeat(50))
    lines.push('')
    lines.push(formatTable(summary.activityTable))
    lines.push('')
  }
  
  // Legend
  lines.push('LEGEND')
  lines.push('-'.repeat(50))
  lines.push('Above Range — The 7-day average is higher than the 75th percentile of your 30-day reference range.')
  lines.push('Below Range — The 7-day average is lower than the 25th percentile of your 30-day reference range.')
  lines.push('Blank — The value is within your normal reference range.')
  lines.push('')
  lines.push('Reference ranges are calculated from your personal historical data (30-day period) using the interquartile range method.')
  lines.push('')
  
  // Disclaimer
  lines.push('DISCLAIMER')
  lines.push('-'.repeat(50))
  lines.push('This report is generated by an experimental tool based on personal health tracking data.')
  lines.push('It is provided "as is" without any warranties, express or implied.')
  lines.push('This report is for informational purposes only and does not constitute medical advice.')
  lines.push('Always seek the advice of a qualified healthcare professional with any questions regarding your health.')
  
  return lines.join('\n')
}

function formatTable(table: Array<{ metric: string; value: string; referenceRange: string; flag: string }>): string {
  const lines: string[] = []
  
  for (const row of table) {
    lines.push(`${row.metric}:`)
    lines.push(`  7 Days values: ${row.value}`)
    lines.push(`  30 Days Reference Range: ${row.referenceRange}`)
    if (row.flag) {
      lines.push(`  Flag: ${row.flag}`)
    }
    lines.push('')
  }
  
  return lines.join('\n')
}
